"""title uniques constraint

Revision ID: d2207d467fbe
Revises: 41d768a62f83
Create Date: 2024-08-28 08:13:59.201157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2207d467fbe'
down_revision: Union[str, None] = '41d768a62f83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_plans_title', table_name='plans')
    op.create_index(op.f('ix_plans_title'), 'plans', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plans_title'), table_name='plans')
    op.create_index('ix_plans_title', 'plans', ['title'], unique=True)
    # ### end Alembic commands ###
