"""Magazine & plan creation 

Revision ID: eaf2b8d62826
Revises: 2a8844836de7
Create Date: 2024-08-12 11:20:58.545229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaf2b8d62826'
down_revision: Union[str, None] = '2a8844836de7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('magazines', sa.Column('discount_quarterly', sa.Float(), nullable=True))
    op.add_column('magazines', sa.Column('discount_half_yearly', sa.Float(), nullable=True))
    op.add_column('magazines', sa.Column('discount_annual', sa.Float(), nullable=True))
    op.drop_column('magazines', 'discount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('magazines', sa.Column('discount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('magazines', 'discount_annual')
    op.drop_column('magazines', 'discount_half_yearly')
    op.drop_column('magazines', 'discount_quarterly')
    # ### end Alembic commands ###
